package HelloApp;

/**
* HelloApp/CryptSysHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 15, 2020 2:13:39 PM MSK
*/

public final class CryptSysHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.CryptSys value = null;

  public CryptSysHolder ()
  {
  }

  public CryptSysHolder (HelloApp.CryptSys initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.CryptSysHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.CryptSysHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.CryptSysHelper.type ();
  }

}
