package HelloApp;

/**
* HelloApp/DecryptSysHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 15, 2020 2:13:39 PM MSK
*/

public final class DecryptSysHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.DecryptSys value = null;

  public DecryptSysHolder ()
  {
  }

  public DecryptSysHolder (HelloApp.DecryptSys initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.DecryptSysHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.DecryptSysHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.DecryptSysHelper.type ();
  }

}
