package HelloApp;


/**
* HelloApp/DecryptSysOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, March 15, 2020 2:13:39 PM MSK
*/

public interface DecryptSysOperations 
{
  String decrypt (String str);
} // interface DecryptSysOperations
